// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRGTrB98L6lj_-sD81JHVc5MNcXWrW1I4',
    appId: '1:181411297717:web:33d63bf2687089602401fc',
    messagingSenderId: '181411297717',
    projectId: 'todo-app-178',
    authDomain: 'todo-app-178.firebaseapp.com',
    storageBucket: 'todo-app-178.appspot.com',
    measurementId: 'G-KT81BNLW6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7DQCPK4B_GEE9Hpl6BuHBCL0fdf0pAuw',
    appId: '1:181411297717:android:bd1771246fd7d2df2401fc',
    messagingSenderId: '181411297717',
    projectId: 'todo-app-178',
    storageBucket: 'todo-app-178.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVgj-5djhDrECX7ZXpoblJzNS21RVyWXo',
    appId: '1:181411297717:ios:b80536869d3595332401fc',
    messagingSenderId: '181411297717',
    projectId: 'todo-app-178',
    storageBucket: 'todo-app-178.appspot.com',
    iosClientId:
        '181411297717-29h3c4aeevfoojtaobqhgepbkdrigg2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
